sim_metric: 'cosine' # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "/workspace/CS762_Project/SemDeDup/code_alpaca_results/emb_mmap.dat"
text_emb_memory_loc: None
paths_memory_loc: "/workspace/CS762_Project/SemDeDup/code_alpaca_results/paths_mmap.dat"
sorted_clusters_file_loc: "/workspace/CS762_Project/SemDeDup/code_alpaca_results/sorted_clusters"
save_folder: "/workspace/CS762_Project/SemDeDup/code_alpaca_results/save_location"
path_str_dtype: "float32"
ncentroids: 20
dataset_size: 200
emb_size: 1024
niter: 100
seed: 1234